var _tmr=_tmr||[];
(function(){function u(a,q,c){a.addEventListener?a.addEventListener(q,c,!1):a.attachEvent&&a.attachEvent("on"+q,c)}function b(){}function F(a){return(a=!l?void 0:l[a])&&v?a-v:void 0}function m(a,q){var d="id"in a?a.id:n,e="url"in a?a.url:location.href,b="referrer"in a?a.referrer:f.referrer,d=("https:"==f.location.protocol?"https:":"http:")+"//top-fwz1.mail.ru"+(q?"/tracker":"/counter")+"?js=13"+(d?";id="+escape(d):"")+(e?";u="+escape(e):"")+(b?";r="+escape(b):"")+("start"in a&&0<a.start?";st="+escape(a.start):
"")+("gender"in a?";gender="+escape(a.gender):"")+("age"in a?";age="+escape(a.age):"")+";title="+encodeURIComponent(f.title)+((w=c.screen)?";s="+w.width+"*"+w.height:"")+";vp=",b=e=0;f.documentElement&&(f.documentElement.clientWidth||f.documentElement.clientHeight)?(e=f.documentElement.clientWidth,b=f.documentElement.clientHeight):"number"==typeof c.innerWidth&&(e=c.innerWidth,b=c.innerHeight);d=d+(""+e+"*"+b)+";touch="+G+";hds="+H+";flash="+x+";sid="+B+";ver="+C+";nt=";if(!l||!y)e="";else{e=[];e.push(y.type);
e.push(y.redirectCount);e.push(v);for(b=0;b<D.length;b++)e.push(F(D[b]));e=e.join("/")}return d+e+";_="+Math.random()}function E(a,b){return("https:"==f.location.protocol?"https:":"http:")+"//top-fwz1.mail.ru/tracker?js=13;id="+a[0]+";e="+escape(b)+";sid="+B+";ids="+a.join()+";ver="+C+";_="+Math.random()}function I(){for(var a=0;a<p.length;a++){var b=p[a];(new Image).src=m(b,!0)+";e="+escape("PVT/15")}}function z(){_tmr.onload()}if("[object Array]"===Object.prototype.toString.call(_tmr)){var c=window,
d=navigator,f=document,w,n=0,C=60,r=[],A=0,s=0,h=[],B="xxxxxxxx".replace(/[x]/g,function(a){return(16*Math.random()|0).toString(16)}),p=[],t=0,G="ontouchstart"in c||1<(d.maxTouchPoints||d.msMaxTouchPoints)?"1":"0",H=c.devicePixelRatio||0,x="";if(d.plugins&&d.plugins["Shockwave Flash"])x=d.plugins["Shockwave Flash"].description.split(" ")[2];else if(c.ActiveXObject)try{var g=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),g=g.GetVariable("$version"),g=g.split(" ")[1].split(","),x=g[0]+"."+g[1]}catch(J){}var d=
c.performance||c.mozPerformance||c.msPerformance||c.webkitPerformance||{},l=d.timing||{},y=d.navigation||{},D="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),v=!l?void 0:l.navigationStart;b.prototype.pageView=function(a){"start"in
a&&r.push(a);(new Image).src=m(a,!1);s=(new Date).getTime()};b.prototype.reachGoal=function(a){"goal"in a&&((new Image).src=m(a,!0)+(a.goal?";e="+escape("RG/"+a.goal):""))};b.prototype.itemView=function(a){if("productid"in a&&("id"in a||n)){var b="id"in a?a.id:n;(new Image).src=("https:"==f.location.protocol?"https:":"http:")+"//ad.mail.ru/retarget/?counter="+b+"&list="+(a.list?a.list:"")+"&productid="+a.productid.toString()+"&pagetype="+(a.pagetype?a.pagetype:"")+"&totalvalue="+(a.totalvalue?a.totalvalue:
0)+"&_="+Math.random()}};b.prototype.processEvent=function(a){if("type"in a&&("pageView"!=a.type||"id"in a)){if("id"in a&&!n&&("pageView"==a.type||"reachGoal"==a.type))n=a.id;switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a)}}};b.prototype.push=function(a){this.processEvent(a)};b.prototype.onload=function(){if(0<r.length){t=(new Date).getTime();for(var a=0,b;b=r[a];a++)(new Image).src=m(b,!0)+";e="+escape("RT/load")+";et="+
t;s=t;r=[]}setTimeout(I,15E3)};b.prototype.beat=function(){if(0!=h.length&&A){var a=(new Date).getTime(),b=a-A;if(!(12E4<b)){if(12E4<a-s)for(var c=0;c<p.length;c++){var d=p[c];(new Image).src=m(d,!0)+";e="+escape("RT/resend")+";et="+t+";active="+(b?"1":"0")}else(new Image).src=E(h,"RT/beat");s=a}}};b.prototype.unload=function(){0!=h.length&&((new Image).src=E(h,"RT/unload"))};b.prototype.activity=function(a){A=(new Date).getTime()};for(var d=new b,g=0,k;k=_tmr[g];g++)"id"in k&&("type"in k&&"pageView"==
k.type&&5>h.length)&&(h.push(k.id),p.push(k)),d.processEvent(k);_tmr=d;if("complete"===f.readyState)_tmr.onload();else c.addEventListener?c.addEventListener("load",z,!1):c.attachEvent?c.attachEvent("onload",z):c.onload=z;u(c,"beforeunload",_tmr.unload);if(h.length){setInterval(_tmr.beat,3E4);try{d=function(a){for(var b=0;b<a.length;b++)u(f,a[b],function(){_tmr.activity(a[b])})},d(["scroll","gesturechange","touchmove"]),d(["mousedown","mousemove","mouseup"]),u(c,"scroll",function(){_tmr.activity("scallback")})}catch(K){}}}})();

